
[jwt-adapter "console"]
    enabled = 1
    priority = 0
    name = console-jwt-adapter


[datagroup "subjects"]
    alias = subjects
    enabled = 1
    table-name-prefix = subjects_
    datasource = main
    uri = uri://data-group/subjects

