
[jwt-codec "default"]
    name = default
    enabled = 1
    priority = 0


[jwt-key-loader "property"]
    enabled = 1
    name = property-key-loader
    priority = 0
    secret = hex:010203040506070809000a0b0c0d0e0f

[jwt-key-loader "main"]
    length = 128
