
[data]
    groups = std-rbac-dg, default


[rbac-data-group "sql"]
    enabled = 1
    priority = 1
    class = rbac-dg std-rbac-dg

[datagroup "std-rbac-dg"]
    alias = std-rbac-dg
    enabled = 1
    uri = uri:datagroup/std-rbac-dg
    table-name-prefix = rbac_dg_
    datasource = main
